dubbo:
  application:
    name: leaf-service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://47.93.20.92:8848
  scan:
    basePackages: com
nacos:
  config:
    server-addr: 47.93.20.92:8848
server:
  port: 18081