dubbo:
  application:
    name: leaf-service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://172.17.62.47:8848
  scan:
    basePackages: com
nacos:
  config:
    server-addr: 172.17.62.47:8848
server:
  port: 18081