dubbo:
  application:
    name: leaf-service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://192.168.11.33:8848
  scan:
    basePackages: com
nacos:
  config:
    server-addr: 192.168.11.33:8848
server:
  port: 18081