dubbo:
  application:
    name: leaf-service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://112.125.27.45:8848
  scan:
    basePackages: com
nacos:
  config:
    server-addr: 112.125.27.45:8848
server:
  port: 18081